name: ci
on:
  push:
jobs:
  test:
    name: Run lint and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: pip install tox wheel setuptools pre-commit
    - name: Run lint
      run: pre-commit run -a
    - name: Run tests
      run: tox -e py
